# Generated by Django 4.1.5 on 2023-01-16 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id_tracking', models.AutoField(primary_key=True, serialize=False)),
                ('track_type', models.CharField(help_text='Código de la empresa de transporte', max_length=16)),
                ('track_code', models.CharField(help_text='Código de seguimiento', max_length=200)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Indica la fecha de creación', verbose_name='Fecha de creación')),
                ('audit_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Indica la fecha de la última actualización', verbose_name='Fecha de actualización')),
                ('expiration_date', models.DateField(help_text='Indica la fecha de vencimiento del paquete', null=True, verbose_name='Fecha de vencimiento')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('sw_allow', models.BooleanField(default=False, help_text='Permite el uso de la aplicación al usuario', verbose_name='Activo')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Indica la fecha de creación del usuario', verbose_name='Fecha de creación')),
                ('audit_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Indica la fecha de la última actualización del usuario', verbose_name='Fecha de actualización')),
            ],
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id_user_attribute', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_key', models.CharField(help_text='Código del atributo', max_length=16)),
                ('attribute_value', models.TextField(help_text='Valor del atributo', max_length=1000)),
                ('audit_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Indica la fecha de la última actualización del atributo', verbose_name='Fecha de actualización')),
                ('id_user_fK', models.ForeignKey(help_text='Identificador de usuario', on_delete=django.db.models.deletion.CASCADE, to='tracking.user')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingDetail',
            fields=[
                ('id_tracking_detail', models.AutoField(primary_key=True, serialize=False)),
                ('detail_head', models.CharField(help_text='Resumen del seguimiento', max_length=200)),
                ('detail_text', models.TextField(help_text='Detalle del seguimiento', max_length=1000)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Indica la fecha de creación', verbose_name='Fecha de creación')),
                ('audit_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Indica la fecha de la última actualización', verbose_name='Fecha de actualización')),
                ('id_tracking_fk', models.ForeignKey(help_text='Identificador del tracking', on_delete=django.db.models.deletion.CASCADE, to='tracking.tracking')),
            ],
        ),
        migrations.AddField(
            model_name='tracking',
            name='id_creator_user_fK',
            field=models.ForeignKey(help_text='Identificador del usuario creador', on_delete=django.db.models.deletion.CASCADE, to='tracking.user'),
        ),
    ]
