# Generated by Django 4.1.5 on 2023-01-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='expiration_date',
            field=models.DateField(help_text='Indica la fecha de vencimiento del paquete', verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddConstraint(
            model_name='trackingdetail',
            constraint=models.UniqueConstraint(fields=('id_tracking_fk', 'detail_head', 'detail_text', 'audit_time'), name='unique tracking detail'),
        ),
    ]
