# Generated by Django 4.1.5 on 2023-02-02 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0002_alter_tracking_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='id_creator_user_fK',
            field=models.ForeignKey(help_text='Identificador del usuario creador', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='expiration_date',
            field=models.DateField(help_text='Indica la fecha de vencimiento del paquete', null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='id_user_fK',
            field=models.ForeignKey(help_text='Identificador de usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
