on:
  push:
    branches: [ dev ]

permissions:
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build_and_upload:
    name: Docker build and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (dev)
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          tags: ${{ env.REGISTRY }}/taixmiguel/taixtrackingv2:dev
          platforms: linux/amd64,linux/arm64
